url: https://magnus.sfenl.org
baseurl: 

# Site settings
title: Project Lumen
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: '@katranrocks'
  pic: 1
  position: Agent Katranrocks is currently conducting research on her thesis regarding fault lines and megafield lanes. Little is known of her earlier career, except it is known that this XM sensitive embarked on a series of highly classified missions for the government in the Eastern Sierras.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: '@UndiKiwi'
  pic: 2
  position: Is a data specialist who actually loves everything about his job. He enjoys the outdoors, especially out sailing on the Bay. He admires Nature in all its Glory sometimes capturing it on film. And, of course, he enjoys chillin’ with Ingress. Oops… there he goes recharging another Portal :-)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
