url: https://magnus.sfenl.org
baseurl: 

# Site settings
title: Project Lumen
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: '@Katranrocks'
  pic: Katranrocks
  position: Agent Katranrocks is currently conducting research on her thesis regarding fault lines and megafield lanes. Little is known of her earlier career, except it is known that this XM sensitive embarked on a series of highly classified missions for the government in the Eastern Sierras.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: '@UndiKiwi'
  pic: UndiKiwi
  position: Is a data specialist who actually loves everything about his job. He enjoys the outdoors, especially out sailing on the Bay. He admires Nature in all its Glory sometimes capturing it on film. And, of course, he enjoys chillin’ with Ingress. Oops… there he goes recharging another Portal :-)
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: @Tomago
  pic: Tomago
  position: Tomago is a virtual arms dealer (it sounds more baller than "farmer"). When she's not busy herding teams of multidisciplinary cats in constructing art installations for festivals, she travels the world, working on her explorer and pioneer badges.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: @Jookwarrior
  pic: Jookwarrior
  position: Jookwarrior is an engineer who loves to tinker, play video games, eat great food, and explore new places. Because this description is actually not terribly descriptive, here are some relatively unknown non-opsec facts: He can play the cello/piano but hasn't done so in years...he can bend his left thumb backwards but not his right...he dislikes beans and taro with a passion...and though he's done the Inca Trail twice and the backside of Half Dome, he's not terribly fond of heights.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
